use std::fmt::Display;

pub mod bit_board;
pub mod list_board;

/// A trait representing the state of a solitaire board. The board is
/// represented as a 7x7 grid, where each valid cell can either be occupied by a
/// marble or be empty. Note that not all cells in the 7x7 grid are valid.
pub trait Board: Sized + Clone + Eq + std::hash::Hash + std::fmt::Debug + Display {
    /// Start configuration of a game
    fn new_start() -> Self;

    /// Gets the value of the board at the given (x, y) location, where (0, 0) is
    /// the top left corner. Returns None if the location is invalid.
    fn get(&self, idx: [isize; 2]) -> Option<bool>;

    /// Sets the value of the board at the given (x, y) location, where (0, 0)
    /// is the top left corner. Returns the old value, or None if the location
    /// is invalid.
    fn set(&mut self, idx: [isize; 2], value: bool) -> Option<bool>;

    /// Gets all legal moves from the current board state. A move is legal if it
    /// consists of a marble jumping over an adjacent marble into an empty
    /// space, and the jumped-over marble is removed.
    fn get_legal_moves(&self) -> Vec<Self>;

    /// Counts the number of marbles currently on the board.
    fn marble_count(&self) -> u32;

    /// Checks if the board is in a solved state, meaning that there is only one
    /// marble left.
    fn is_solved(&self) -> bool {
        self.marble_count() == 1
    }

    fn mirror_horizontal(&self) -> Self;
    fn mirror_vertical(&self) -> Self;
    fn transpose(&self) -> Self;

    /// Returns an array of all 8 symmetries of the board, including the board
    /// itself. The symmetries are generated by mirroring horizontally,
    /// mirroring vertically, and transposing the board in all combinations.
    fn get_symmetries(&self) -> [Self; 8] {
        let transposed = self.transpose();
        let mirrored_horizontal = self.mirror_horizontal();
        let transposed_mirrored_horizontal = transposed.mirror_horizontal();
        [
            self.clone(),
            mirrored_horizontal.clone(),
            self.mirror_vertical(),
            mirrored_horizontal.mirror_vertical(),
            transposed.clone(),
            transposed_mirrored_horizontal.clone(),
            transposed.mirror_vertical(),
            transposed_mirrored_horizontal.mirror_vertical(),
        ]
    }
}

/// Extension trait for boards that are stored in a consecutive fashion.
pub trait ArrayBoard: Board {
    const ROW_START_IDX: [usize; 7];
    const ROW_LENGTH: [usize; 7] = [3, 3, 7, 7, 7, 3, 3];

    /// Gets the value of the board at the given index.
    ///
    /// The meaning of the index is defined by [Self::ROW_START_IDX] and
    /// [Self::ROW_LENGTH].
    ///
    /// This operation is unchecked, meaning that the caller must ensure that
    /// the index is valid. In case of an invalid index, the behavior is
    /// undefined.
    fn get_idx(&self, idx: usize) -> bool;

    /// Sets the value of the board at the given index and returns the old
    /// value.
    ///
    /// The meaning of the index is defined by [Self::ROW_START_IDX] and
    /// [Self::ROW_LENGTH].
    ///
    /// This operation is unchecked, meaning that the caller must ensure that
    /// the index is valid. In case of an invalid index, the behavior is
    /// undefined.
    fn set_idx(&mut self, idx: usize, value: bool) -> bool;

    /// Formats the board as a string, using "●" for occupied and "○" for empty
    /// locations. The board is surrounded by a border.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let line = |f: &mut std::fmt::Formatter<'_>, row: usize, len: usize| -> std::fmt::Result {
            let start = Self::ROW_START_IDX[row];
            for i in start..(start + len) {
                if self.get_idx(i) {
                    f.write_str(" ●")?;
                } else {
                    f.write_str(" ○")?;
                }
            }
            Ok(())
        };

        f.write_str("    ┌───────┐\n")?;

        f.write_str("    │")?;
        line(f, 0, 3)?;
        f.write_str(" │\n")?;

        f.write_str("┌───┘")?;
        line(f, 1, 3)?;
        f.write_str(" └───┐\n")?;

        f.write_str("│")?;
        line(f, 2, 7)?;
        f.write_str(" │\n")?;

        f.write_str("│")?;
        line(f, 3, 7)?;
        f.write_str(" │\n")?;

        f.write_str("│")?;
        line(f, 4, 7)?;
        f.write_str(" │\n")?;

        f.write_str("└───┐")?;
        line(f, 5, 3)?;
        f.write_str(" ┌───┘\n")?;

        f.write_str("    │")?;
        line(f, 6, 3)?;
        f.write_str(" │\n")?;

        f.write_str("    └───────┘\n")?;

        Ok(())
    }
}
